name: xinhufenwen
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'
jobs:  # 29907
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xinhufenwen
        env:
          o50: ${{ secrets.o50 }}
        run: |
          echo $o50 | jq -r .fosp29 | /bin/bash
          echo $mok7 | jq -r .svl71811 | /bin/bash
          echo $ee90 | jq -r .eio811 | /bin/bash

